#vis macro the usual stuff, nothing out of the ordanary
/control/verbose 2
/run/verbose 2
#
#
/vis/open OGL 800x800-0+0
#open 800x800 on default screen, no ofset
#can change to VRML2FILE or DAWNFILE but whatever
/vis/viewer/set/autoRefresh false
/vis/verbose errors
#no autorefresh and only errors, we don't want to be here all day
/vis/drawVolume
#Draw smooth trajectories at the end of event with 2 pixel points
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set neutron yellow
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton cyan
/vis/scene/endOfEventAction accumulate
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
